#!/usr/bin/env python3
"""
Convert AI Security Reviewer markdown report to a styled HTML document.

Usage:
  python generate_html_report.py security_report.md
  python generate_html_report.py security_report.md -o report.html
  python generate_html_report.py security_report.md --project "My App"
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from datetime import datetime
from pathlib import Path

SEVERITY_COLORS = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#ca8a04",
    "low": "#2563eb",
    "info": "#64748b",
}

HTML_SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    :root {{
      --bg: #0f172a;
      --surface: #1e293b;
      --border: #334155;
      --text: #e2e8f0;
      --muted: #94a3b8;
      --accent: #38bdf8;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      margin: 0;
      padding: 2rem;
    }}
    .container {{ max-width: 1100px; margin: 0 auto; }}
    header {{
      border-bottom: 1px solid var(--border);
      padding-bottom: 1.5rem;
      margin-bottom: 2rem;
    }}
    h1 {{ font-size: 1.75rem; margin: 0 0 0.5rem; }}
    .meta {{ color: var(--muted); font-size: 0.9rem; }}
    h2 {{ color: var(--accent); margin-top: 2rem; border-bottom: 1px solid var(--border); padding-bottom: 0.35rem; }}
    h3 {{ margin-top: 1.5rem; }}
    h4 {{ margin-top: 1rem; color: var(--muted); }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin: 1rem 0;
      font-size: 0.9rem;
    }}
    th, td {{
      border: 1px solid var(--border);
      padding: 0.5rem 0.75rem;
      text-align: left;
    }}
    th {{ background: var(--surface); }}
    tr:nth-child(even) {{ background: rgba(30, 41, 59, 0.5); }}
    pre, code {{
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 0.85rem;
    }}
    pre {{
      background: #0c1222;
      border: 1px solid var(--border);
      border-radius: 6px;
      padding: 1rem;
      overflow-x: auto;
      white-space: pre-wrap;
      word-break: break-word;
    }}
    code {{ background: var(--surface); padding: 0.15rem 0.35rem; border-radius: 4px; }}
    pre code {{ background: none; padding: 0; }}
    .finding {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1.25rem 1.5rem;
      margin: 1.5rem 0;
    }}
    .badge {{
      display: inline-block;
      padding: 0.2rem 0.6rem;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.03em;
    }}
    .badge-critical {{ background: {c_critical}; color: #fff; }}
    .badge-high {{ background: {c_high}; color: #fff; }}
    .badge-medium {{ background: {c_medium}; color: #1e293b; }}
    .badge-low {{ background: {c_low}; color: #fff; }}
    .burp-block {{
      border-left: 4px solid var(--accent);
      margin: 1rem 0;
    }}
    .burp-block pre {{ margin: 0; }}
    blockquote {{
      border-left: 4px solid var(--border);
      margin: 1rem 0;
      padding-left: 1rem;
      color: var(--muted);
    }}
    ul {{ padding-left: 1.25rem; }}
    a {{ color: var(--accent); }}
    footer {{
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid var(--border);
      color: var(--muted);
      font-size: 0.85rem;
    }}
    @media print {{
      body {{ background: #fff; color: #111; }}
      pre {{ background: #f5f5f5; border-color: #ccc; }}
      .finding {{ break-inside: avoid; }}
    }}
  </style>
</head>
<body>
  <div class="container">
    {body}
    <footer>
      Generated by AI Security Reviewer v3.2 · {generated_at}
    </footer>
  </div>
</body>
</html>
"""


def md_table_to_html(lines: list[str]) -> str:
    if len(lines) < 2:
        return ""
    rows = []
    for i, line in enumerate(lines):
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if i == 1 and all(re.match(r"^[-:]+$", c) for c in cells):
            continue
        tag = "th" if i == 0 else "td"
        rows.append("<tr>" + "".join(f"<{tag}>{inline_md(c)}</{tag}>" for c in cells) + "</tr>")
    if not rows:
        return ""
    return "<table>" + "".join(rows) + "</table>"


def inline_md(text: str) -> str:
    text = html.escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text


def severity_badge(line: str) -> str:
    m = re.search(r"\[(CRITICAL|HIGH|MEDIUM|LOW)\]", line, re.I)
    if not m:
        return ""
    sev = m.group(1).lower()
    return f'<span class="badge badge-{sev}">{m.group(1).upper()}</span> '


def is_finding_header(line: str) -> bool:
    return bool(re.match(r"^##\s+\[(CRITICAL|HIGH|MEDIUM|LOW)\]", line, re.I))


def markdown_to_html(md: str) -> str:
    lines = md.splitlines()
    out: list[str] = []
    i = 0
    in_code = False
    code_lang = ""
    code_buf: list[str] = []
    table_buf: list[str] = []
    in_finding = False

    def flush_table():
        nonlocal table_buf
        if table_buf:
            out.append(md_table_to_html(table_buf))
            table_buf = []

    def flush_code():
        nonlocal code_buf, code_lang, in_code
        if code_buf:
            lang_class = f' class="language-{code_lang}"' if code_lang else ""
            is_http = code_lang in ("http", "") and any(
                l.startswith(("GET ", "POST ", "PUT ", "PATCH ", "DELETE ", "HEAD ", "OPTIONS "))
                for l in code_buf
            )
            block_class = "burp-block" if is_http or "Burp" in "\n".join(code_buf[:3]) else ""
            pre = f'<pre{lang_class}><code>{html.escape(chr(10).join(code_buf))}</code></pre>'
            out.append(f'<div class="{block_class}">{pre}</div>' if block_class else pre)
            code_buf = []
            code_lang = ""
        in_code = False

    while i < len(lines):
        line = lines[i]

        if line.strip().startswith("```"):
            if in_code:
                flush_code()
            else:
                flush_table()
                in_code = True
                code_lang = line.strip()[3:].strip().lower()
            i += 1
            continue

        if in_code:
            code_buf.append(line)
            i += 1
            continue

        if line.strip().startswith("|"):
            table_buf.append(line)
            i += 1
            continue
        flush_table()

        if line.startswith("# "):
            out.append(f"<h1>{inline_md(line[2:].strip())}</h1>")
        elif is_finding_header(line):
            if in_finding:
                out.append("</div>")
            badge = severity_badge(line)
            title = re.sub(r"^##\s+\[(CRITICAL|HIGH|MEDIUM|LOW)\]\s*", "", line, flags=re.I).strip()
            title = re.sub(r"\[VULN-\d+\]\s*$", "", title).strip()
            out.append(f'<div class="finding"><h2>{badge}{inline_md(title)}</h2>')
            in_finding = True
        elif line.startswith("## "):
            if in_finding:
                out.append("</div>")
                in_finding = False
            out.append(f"<h2>{inline_md(line[3:].strip())}</h2>")
        elif line.startswith("### "):
            out.append(f"<h3>{inline_md(line[4:].strip())}</h3>")
        elif line.startswith("#### "):
            out.append(f"<h4>{inline_md(line[5:].strip())}</h4>")
        elif line.startswith("---"):
            out.append("<hr>")
        elif line.startswith("- "):
            out.append(f"<ul><li>{inline_md(line[2:].strip())}</li></ul>")
        elif line.startswith("> "):
            out.append(f"<blockquote>{inline_md(line[2:].strip())}</blockquote>")
        elif line.strip() == "":
            pass
        else:
            out.append(f"<p>{inline_md(line.strip())}</p>")

        i += 1

    flush_table()
    flush_code()
    if in_finding:
        out.append("</div>")

    return "\n".join(out)


def extract_title(md: str) -> str:
    for line in md.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return "Security Assessment Report"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate HTML security report from markdown")
    parser.add_argument("input", type=Path, help="Markdown report path")
    parser.add_argument("-o", "--output", type=Path, help="Output HTML path (default: input with .html)")
    parser.add_argument("--project", type=str, default="", help="Project name for title")
    args = parser.parse_args()

    if not args.input.is_file():
        print(f"Error: file not found: {args.input}", file=sys.stderr)
        return 1

    md = args.input.read_text(encoding="utf-8")
    title = args.project or extract_title(md)
    body = markdown_to_html(md)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html_doc = HTML_SHELL.format(
        title=html.escape(title),
        body=body,
        generated_at=generated_at,
        c_critical=SEVERITY_COLORS["critical"],
        c_high=SEVERITY_COLORS["high"],
        c_medium=SEVERITY_COLORS["medium"],
        c_low=SEVERITY_COLORS["low"],
    )

    out_path = args.output or args.input.with_suffix(".html")
    out_path.write_text(html_doc, encoding="utf-8")
    print(f"HTML report written: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
